from enum import Enum


class WorkflowState(str, Enum):
    DISCOVERED = "DISCOVERED"
    VERIFIED = "VERIFIED"
    WEBSITE_ANALYZED = "WEBSITE_ANALYZED"
    SCORED = "SCORED"
    QUALIFIED = "QUALIFIED"
    DECISION_MAKER_RESEARCHED = "DECISION_MAKER_RESEARCHED"
    BUSINESS_AUDITED = "BUSINESS_AUDITED"
    DEMO_GENERATED = "DEMO_GENERATED"
    OUTREACH_DRAFTED = "OUTREACH_DRAFTED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    CONTACTED = "CONTACTED"
    REPLIED = "REPLIED"
    QUALIFIED_OPPORTUNITY = "QUALIFIED_OPPORTUNITY"
    WON = "WON"
    LOST = "LOST"
    
    # Rejection / Suppression States
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    DO_NOT_CONTACT = "DO_NOT_CONTACT"


class WebsiteStatus(str, Enum):
    NO_WEBSITE = "NO_WEBSITE"
    WEBSITE_FOUND = "WEBSITE_FOUND"
    WEAK_WEBSITE = "WEAK_WEBSITE"
    WEBSITE_UNREACHABLE = "WEBSITE_UNREACHABLE"
    WEBSITE_UNVERIFIED = "WEBSITE_UNVERIFIED"


class VerificationStatus(str, Enum):
    VERIFIED = "VERIFIED"
    PARTIALLY_VERIFIED = "PARTIALLY_VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    REJECTED = "REJECTED"


class ConfidenceLevel(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    NOT_FOUND = "NOT_FOUND"


class OutreachStatus(str, Enum):
    DRAFTED = "DRAFTED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DISPATCHED = "DISPATCHED"
    DRY_RUN_LOGGED = "DRY_RUN_LOGGED"


class EntityType(str, Enum):
    BUSINESS = "BUSINESS"
    NON_BUSINESS = "NON_BUSINESS"
    UNCERTAIN = "UNCERTAIN"


class EntityVerificationStatus(str, Enum):
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class WebsiteHealthState(str, Enum):
    SITE_ACCESSIBLE = "SITE_ACCESSIBLE"
    DNS_FAILURE = "DNS_FAILURE"
    DOMAIN_NOT_FOUND = "DOMAIN_NOT_FOUND"
    CONNECTION_TIMEOUT = "CONNECTION_TIMEOUT"
    HTTP_403 = "HTTP_403"
    HTTP_404 = "HTTP_404"
    HTTP_429 = "HTTP_429"
    HTTP_5XX = "HTTP_5XX"
    SSL_ERROR = "SSL_ERROR"
    TEMPORARILY_UNAVAILABLE = "TEMPORARILY_UNAVAILABLE"
    CONTENT_UNVERIFIED = "CONTENT_UNVERIFIED"
    UNKNOWN = "UNKNOWN"


class WebsiteVerificationStatus(str, Enum):
    OFFICIAL_WEBSITE_VERIFIED = "OFFICIAL_WEBSITE_VERIFIED"
    WEBSITE_FOUND_UNVERIFIED = "WEBSITE_FOUND_UNVERIFIED"
    NO_WEBSITE_CONFIRMED = "NO_WEBSITE_CONFIRMED"
    CONFLICTING_WEBSITES = "CONFLICTING_WEBSITES"
    CONTENT_UNVERIFIED = "CONTENT_UNVERIFIED"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class WebsiteClassification(str, Enum):
    NO_WEBSITE = "NO_WEBSITE"
    WEAK_WEBSITE = "WEAK_WEBSITE"
    OUTDATED_WEBSITE = "OUTDATED_WEBSITE"
    POOR_UX = "POOR_UX"
    POOR_CONVERSION = "POOR_CONVERSION"
    TECHNICALLY_GOOD = "TECHNICALLY_GOOD"
    GOOD_WEBSITE = "GOOD_WEBSITE"
    EXCELLENT_WEBSITE = "EXCELLENT_WEBSITE"
    CONFLICTING = "CONFLICTING"
    CONTENT_UNVERIFIED = "CONTENT_UNVERIFIED"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class OutreachReadiness(str, Enum):
    NOT_READY = "NOT_READY"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    READY_FOR_APPROVAL = "READY_FOR_APPROVAL"
    APPROVED = "APPROVED"
    SUPPRESSED = "SUPPRESSED"
    CONTACTED = "CONTACTED"


class DemoAccessStatus(str, Enum):
    LOCAL_ONLY = "LOCAL_ONLY"
    PUBLIC_ACCESSIBLE = "PUBLIC_ACCESSIBLE"
    PUBLIC_ACCESS_UNKNOWN = "PUBLIC_ACCESS_UNKNOWN"
    PUBLIC_ACCESS_FAILED = "PUBLIC_ACCESS_FAILED"
    NOT_GENERATED = "NOT_GENERATED"


class ContactTargetStatus(str, Enum):
    VERIFIED_PERSON = "VERIFIED_PERSON"
    VERIFIED_ROLE = "VERIFIED_ROLE"
    BUSINESS_CONTACT_ONLY = "BUSINESS_CONTACT_ONLY"
    NOT_FOUND = "NOT_FOUND"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class ManualReviewStatus(str, Enum):
    NO_REVIEW_REQUIRED = "NO_REVIEW_REQUIRED"
    REVIEW_RECOMMENDED = "REVIEW_RECOMMENDED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class QualificationStatus(str, Enum):
    PRIORITY = "PRIORITY"
    QUALIFIED = "QUALIFIED"
    POTENTIAL_REVIEW = "POTENTIAL_REVIEW"
    REJECTED = "REJECTED"


class DemoReadiness(str, Enum):
    NOT_GENERATED = "NOT_GENERATED"
    LOCAL_ONLY = "LOCAL_ONLY"
    PUBLIC_ACCESS_UNKNOWN = "PUBLIC_ACCESS_UNKNOWN"
    PUBLIC_ACCESS_FAILED = "PUBLIC_ACCESS_FAILED"
    PUBLIC_ACCESSIBLE = "PUBLIC_ACCESSIBLE"


class FinalAction(str, Enum):
    AWAITING_HUMAN_OUTREACH_APPROVAL = "AWAITING_HUMAN_OUTREACH_APPROVAL"
    REQUIRES_MANUAL_REVIEW = "REQUIRES_MANUAL_REVIEW"
    REVIEW_RECOMMENDED = "REVIEW_RECOMMENDED"
    REJECTED = "REJECTED"
    QUALIFIED_NOT_READY = "QUALIFIED_NOT_READY"




