from enum import Enum


class WorkflowState(str, Enum):
    DISCOVERED = "DISCOVERED"
    VERIFIED = "VERIFIED"
    WEBSITE_ANALYZED = "WEBSITE_ANALYZED"
    SCORED = "SCORED"
    QUALIFIED = "QUALIFIED"
    DECISION_MAKER_RESEARCHED = "DECISION_MAKER_RESEARCHED"
    BUSINESS_AUDITED = "BUSINESS_AUDITED"
    DEMO_GENERATED = "DEMO_GENERATED"
    OUTREACH_DRAFTED = "OUTREACH_DRAFTED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    CONTACTED = "CONTACTED"
    REPLIED = "REPLIED"
    QUALIFIED_OPPORTUNITY = "QUALIFIED_OPPORTUNITY"
    WON = "WON"
    LOST = "LOST"
    
    # Rejection / Suppression States
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    DO_NOT_CONTACT = "DO_NOT_CONTACT"


class WebsiteStatus(str, Enum):
    NO_WEBSITE = "NO_WEBSITE"
    WEBSITE_FOUND = "WEBSITE_FOUND"
    WEAK_WEBSITE = "WEAK_WEBSITE"
    WEBSITE_UNREACHABLE = "WEBSITE_UNREACHABLE"
    WEBSITE_UNVERIFIED = "WEBSITE_UNVERIFIED"


class VerificationStatus(str, Enum):
    VERIFIED = "VERIFIED"
    PARTIALLY_VERIFIED = "PARTIALLY_VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    REJECTED = "REJECTED"


class ConfidenceLevel(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    NOT_FOUND = "NOT_FOUND"


class OutreachStatus(str, Enum):
    DRAFTED = "DRAFTED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DISPATCHED = "DISPATCHED"
    DRY_RUN_LOGGED = "DRY_RUN_LOGGED"
